/**
 * Removes a leading `post-link` from the `post`'s `.content`
 * if it satisfies `shouldRemovePostLink()` condition.
 * Can be used to remove redundant parent post quotes
 * when showing the parent post's replies tree.
 * @param  {object} post
 * @param  {(any|function)} postLinkTest — The condition for removing a post link: either a post id or a function that returns `true` when the post link should be removed.
 */
export default function removeLeadingPostLink(post, postLinkTest) {
	const content = removeLeadingPostLinkFromContent(post.content, postLinkTest)
	// If no leading post link has been removed.
	if (content === post.content) {
		return post
	}
	return {
		...post,
		content
	}
}

function removeLeadingPostLinkFromContent(content, postLinkTest) {
	if (content) {
		const paragraph = content[0]
		if (Array.isArray(paragraph)) {
			const firstPart = paragraph[0]
			if (typeof firstPart === 'object' &&
				firstPart.type === 'post-link' &&
				shouldRemovePostLink(firstPart, postLinkTest)) {
				const postLinkHasQuotes = Array.isArray(firstPart.content) && firstPart.content[0].type === 'quote'
				// Only remove autogenerated `post-link`s
				// or `post-link`s having no quotes.
				// If a `post-link` contains a quote posted manually
				// by the post author then don't remove such quote.
				// If a post link content is not a "quote" then
				// it's something autogenerated like "Comment".
				if (!postLinkHasQuotes || firstPart.content[0].generated) {
					if (paragraph.length === 1) {
						if (content.length === 1) {
							return
						} else {
							return content.slice(1)
						}
					} else if (paragraph[1] === '\n') {
						if (paragraph.length === 2) {
							if (content.length === 1) {
								return
							} else {
								return content.slice(1)
							}
						} else {
							if (content.length === 1) {
								return [paragraph.slice(2)]
							} else {
								return [paragraph.slice(2)].concat(content.slice(1))
							}
						}
					}
				}
			}
		}
	}
	return content
}

function shouldRemovePostLink(postLink, postLinkTest) {
	if (typeof postLinkTest === 'function') {
		return postLinkTest(postLink)
	}
	return postLink.postId === postLinkTest
}